config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[ index edit show update]
  resources :projects do
    get :created, on: :collection
  end
  root to: 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :projects

  def to_s
    name
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: { :maximum => 200}
  validates :start_date, presence: true
  validates :delivery_date, presence: true
  validate :delivery_date_must_be_in_future, :start_date_validation, on: :create, on: :update
  validates :company, :description, :source_language, :subject_area, :source_file, :user,  presence: true
  belongs_to :company
  belongs_to :source_language
  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :projects) }  counter cache for old records
  belongs_to :subject_area

  has_many :project_target_languages
  has_many :target_languages, through: :project_target_languages, dependent: :destroy


  extend FriendlyId
  friendly_id :name, use: :slugged

  has_rich_text :description
  has_rich_text :instructions

  mount_uploader :source_file,    FileUploader
  mount_uploader :reference_file, FileUploader

  def to_s
    name
  end

  def start_date_validation
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "must be in the future")
    elsif start_date.present? && delivery_date.present?  && start_date > delivery_date
      errors.add(:start_date, " cannot be after delivery date")
    end
  end

  def delivery_date_must_be_in_future
    if delivery_date.present? && delivery_date < Date.today + 2
      errors.add(:delivery_date, "must be at least 2 days from today")
    end
  end

end

app/models/project_target_language.rb
class ProjectTargetLanguage < ApplicationRecord
  belongs_to :project
  belongs_to :target_language

  validates :project, :target_language, presence: true
  
  validates_uniqueness_of :project_id, scope: :target_language_id 
  validates_uniqueness_of :target_language_id, scope: :project_id 
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/source_language.rb
class SourceLanguage < ApplicationRecord
  has_many :projects

  def to_s
    name
  end
  
end

app/models/subject_area.rb
class SubjectArea < ApplicationRecord
  has_many :projects

  def to_s
    name
  end
end

app/models/target_language.rb
class TargetLanguage < ApplicationRecord
  has_many :project_target_languages
  has_many :projects, through: :project_target_languages

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  rolify

  extend FriendlyId
  friendly_id :email, use: :slugged

  after_create :assign_default_role
  #make sure that each user on the system has at least one roll
  validate :must_have_a_role, on: :update
  has_many :projects

  def to_s
    username
  end

  def username
    self.email.split(/@/).first
  end


  def online?
    updated_at > 2.minutes.ago
  end

  def assign_default_role
    # If first User of the system, he will be an admin, otherwise he will be a teacher and a studnet
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:client)
    else
    self.add_role(:client) if self.roles.blank?
    end
  end

  private
  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "Must have at least one role")
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pagy::Backend
  
  include Pundit
  before_action :set_global_action, if: :user_signed_in?

  def set_global_action
    @ransack_path = created_projects_path
    @ransack_projects = Project.where({user: current_user}).ransack(params[:projects_search], search_key: :projects_search)
    @pagy, @projects = pagy(@ransack_projects.result.includes(:user))
    # @ransack_projects = Project.ransack(params[:projects_search], search_key: :projects_search) #navbar search
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @ransack_path = projects_path
    @ransack_projects = Project.where({user: current_user}).ransack(params[:projects_search], search_key: :projects_search)
    
    @pagy, @projects = pagy(@ransack_projects.result.includes(:user)) # allow searching using tag through course_tags 
    authorize @projects
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def created 
    @ransack_path = created_projects_path
    @ransack_projects = Project.where({user: current_user}).ransack(params[:projects_search], search_key: :projects_search)
    @pagy, @projects = pagy(@ransack_projects.result.includes(:user))
    render 'index'
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        ProjectMailer.new_project(@project).deliver_later
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
    
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to created_projects_path, notice: "Project was successfully destroyed." }
    end
  end

  private
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :start_date, :delivery_date, :company_id, :user_id, :source_language_id, :subject_area_id, :description, :instructions, :reference_file, :source_file, target_language_ids: [])
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def index
    @projects_count = Project.all.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def index
    @q = User.ransack(params[:q])
    #@users = @q.result(distinct: true)
    @pagy, @users = pagy(@q.result(distinct: true).order(created_at: :desc))
    authorize @users
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: 'User roles were successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit({role_ids: []})
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  # Returns 'active' if the current path is the active class, otherwise empty
  def active?(test_path)
    return 'active' if current_page? test_path
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_header.haml
%nav.navbar.navbar-expand-lg.navbar-dark.purple-background
  .container-fluid
    %a.navbar-brand{:href => "/"} 
    -# = image_tag 'logo.jpg', size: '60x40', alt: "logo"
    .m-1
    Projectly
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if current_user
        %ul.navbar-nav.mr-auto
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
            = link_to root_path, class: 'nav-link' do
              .fa.fa-home
              Home
          - if current_user && current_user.has_role?(:admin)
            %li.nav-item{class: "#{'active font-weight-bold' if current_page?(projects_path)}"}
              = link_to projects_path, class: 'nav-link' do
                .fas.fa-project-diagram
                Projects
              
          //SEARCH IN NAVBAR
          = search_form_for @ransack_projects, as: :projects_search, url: created_projects_path do |f|
            .input-group
              = f.search_field :name_or_description_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a project', :autocomplete => :off
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"}
              
        %ul.navbar-nav.ms-auto
          - if current_user.has_role?(:client)
            %li.nav-item.dropdown
              %a#clientDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-chalkboard-client
                Projects
              .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "clientDropdown"}
                = link_to new_project_path, class: "dropdown-item #{'active fw-bold' if current_page?(new_project_path)}" do
                  .fas.fa-project-diagram
                  .fa.fa-plus
                  %b New Project
                = link_to created_projects_path, class: "dropdown-item #{'active fw-bold' if current_page?(created_projects_path)}" do
                  .fas.fa-project-diagram
                  %b My Projects
                  .badge.bg-info
                    = current_user.projects_count
            
          - if current_user.has_role?(:admin)
            %li.nav-item.dropdown
              %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-user-cog
                Admin
              .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "adminDropdown"}
                = link_to users_path, class: "dropdown-item #{'active fw-bold' if current_page?(users_path)}" do
                  .fa.fa-users
                  %b Users
                  .badge.bg-info
                    = User.count
                = link_to projects_path, class: "dropdown-item #{'active fw-bold' if current_page?(projects_path)}" do
                  .fas.fa-project-diagram
                  %b All Projects
                  .badge.bg-info
                    = Project.count
                  
              
        %ul.navbar-nav.ms-auto
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              %b= current_user.email
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
              = link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do
                .fa.fa-cog
                %b Account settings
              = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
                .fa.fa-sign-out-alt
                %b Sign out
      - else
        %ul.navbar-nav.ms-auto.mb-2.mb-lg-0
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}"}
            = link_to 'Register', new_user_registration_path, class: 'nav-link'
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_session_path)}"}
            = link_to 'Login', new_user_session_path, class: 'nav-link'
          -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(user_google_oauth2_omniauth_authorize_path)}"}
          -#   = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'nav-link' do
          -#     .fab.fa-google
          -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(user_github_omniauth_authorize_path)}"}
          -#   = link_to user_github_omniauth_authorize_path, method: :post, class: 'nav-link' do
          -#     .fab.fa-github
          -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(user_facebook_omniauth_authorize_path)}"}
          -#   = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'nav-link' do
          -#     .fab.fa-facebook
          
      
          

app/views/layouts/_messages.haml
// Centralize alert for the whole app
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-warning alert-dismissible fade show -#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.btn-close{"aria-hidden" => "true", "data-bs-dismiss" => "alert", :type => "button"}
      = content_tag :div, msg, :id => "flash_#{name}" 

app/views/layouts/application.haml
!!!
%html
  %head
    %title RailsProject
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render "layouts/header"
      = render "layouts/messages"
      %p
      = yield

app/views/projects/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  - if @project.errors.any?
    .container.text-danger
      - @project.errors.full_messages.each do |msg|
        %li= msg
  
  .form-inputs
    .row
      .col-md-6
        = f.input :name
        = f.input :start_date,as: :date, html5: true
        = f.input :delivery_date,as: :date, html5: true
        = f.association :company, as: :radio_buttons, :item_wrapper_class => 'horizontal'

      .col-md-6
        = f.association :source_language, as: :radio_buttons, :item_wrapper_class => 'horizontal'
        = f.association :subject_area, as: :radio_buttons, :item_wrapper_class => 'horizontal'
        %p
        = f.association :target_languages, as: :check_boxes, :item_wrapper_class => 'horizontal'
    %p
    = f.input :description, as: :rich_text_area
    %p
    = f.input :instructions, as: :rich_text_area
    %p
    .row 
      .col-md-6
        = f.label :reference_file
        = f.file_field :reference_file
      .col-md-6
        = f.label :source_file
        = f.file_field :source_file
    %p
  .form-actions
    = f.button :submit, class: "btn btn-success"

app/views/projects/_project.haml
.p-3
.row
  .col-md-8
    %b Project Name:
    = project.name
    .fas.fa-globe-europe.m-1
    %b Source languages:
    = project.source_language.code
    .fas.fa-globe-europe.m-1
    %b Target languages:
    = project.target_languages.pluck(:code)
  .col-md-4
    .fas.fa-clock
    %b Start Date:
    = project.start_date
    .fas.fa-clock
    %b Delivery Date:
    = project.delivery_date
.row
  %p
  .col-md-8
    .fas.fa-building
    %b Company:
    = project.company
    %p
    .fas.fa-book
    %b Subject area:
    = project.subject_area
    %p
  .col-md-4
    -if project.reference_file.url
      .fas.fa-file
      %b Reference file:
      = link_to 'Preview File', project.reference_file.url
    %p
    -if project.source_file.url
      .fas.fa-file
      %b Source file:
      = link_to 'Preview File', project.source_file.url
  %p

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', created_projects_path

app/views/projects/index.html.haml
.text-center 
  %h1 Projects 
.text-end
  = link_to 'New Project', new_project_path, class: "btn btn-primary"
%p

- @projects.each do |project|
  %p
  .card
    .card-header
      .text-center 
        .h4 
          Project:
          = link_to project.name, project_path(project)
      
    .card-body
      = render 'project', project: project
    
    .card-footer 
      = link_to 'Delete Project', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
    
%br
!= pagy_bootstrap_nav(@pagy)

app/views/projects/new.html.haml
- content_for :title do
  Projectly
  \/
  Project
  = @project.name
  \/
  New Project
= link_to 'Projects', projects_path
\/
New Project
%p
.card
  .card-header
    %h3 
      .far.fa-check-square
      New Project
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to projects', created_projects_path, class: "btn btn-warning"

app/views/projects/show.html.haml
- content_for :name do
  Projectly
  \|
  = @project.name
= link_to 'Projects', created_projects_path
\/
= link_to @project.name, project_path(@project)
%p
.text-center 
  .h4 
    Project name:
    = @project.name
.text-end
  = link_to 'Edit Project', edit_project_path(@project), class: "btn btn-primary"
%p
.row
  // for browser resize
  .card
    .card-header
    .card-body
      = render 'project', project: @project
      .row
        .col-md-6
          %b Description:
          = @project.description
        .col-md-6
          %b Instructions:
          = @project.instructions

%br
= link_to 'Back to projects', created_projects_path, class: "btn btn-warning"

app/views/site/index.haml
.card
  .card-header
    .text-center 
      .h4 
        Welcome to Projectly:
      
  .card-body
    .text-center 
      %h1 Projects created so far:
      %h2 
        = @projects_count

  - if current_user.nil?
    .card-footer
      .text-center 
        = link_to "Create Account", new_user_registration_path, class: "btn btn-dark"
        %p
        %b Already a user? 
        = link_to "Login instead", new_user_session_path, class: "btn btn-primary"

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.username
  .card-body
    Signed Up
    = time_ago_in_words(user.created_at)  
    ago

  .card-footer 
    - user.roles.each do |role|
      .badge.bg-info
        = role.name
    %p
    = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning'

app/views/users/edit.html.haml
.card
  .card-header
    Editing roles for
    = @user.email
  .card-body
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: "btn btn-success"
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
.text-center
  Users
  .badge.bg-info
    = @users.count
.form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'   
    = f.submit
  .ml-2
  = link_to 'refresh', users_path
.table-responsive
  %table.table.table-bordered
    %thead
      %tr
        %th id
        %th= sort_link(@q, :email)
        %th= sort_link(@q, :created_at)
        %th= sort_link(@q, :projects_count)
        %th= 'Roles'
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td 
            - if user.online?
              .text-success.fas.fa-circle
            - else
              .text-danger.fas.fa-circle
            =link_to user.email, user_path(user)
          %td= user.created_at
          %td= user.projects_count
          %td 
            - user.roles.each do |role|
              .badge.bg-info
                = role.name
            - if policy(user).edit?
              = link_to "Edit Roles", edit_user_path(user), class: "btn btn-sm btn-warning"
    %p
// if only 1 page, hide pagination
!= pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 